// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBranches():Promise<Array<string>>;

export function GetGitStatus():Promise<string>;
